server:
  port: 8083
spring:
  datasource:
    password: Kiran*123#
    url: jdbc:mysql://localhost:3306/my_projects
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
